version: '3'

services:
    postgres:
        image: postgres:12.2
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=capstone_website
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres

        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: