"""empty message

Revision ID: 269a0316ec24
Revises: 9641fdcfd15e
Create Date: 2020-11-30 17:11:08.150275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269a0316ec24'
down_revision = '9641fdcfd15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_info', sa.Column('returns', sa.Float(), nullable=True))
    op.add_column('portfolio_info', sa.Column('sharpe_ratio', sa.Float(), nullable=True))
    op.add_column('portfolio_info', sa.Column('volatility', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_info', 'volatility')
    op.drop_column('portfolio_info', 'sharpe_ratio')
    op.drop_column('portfolio_info', 'returns')
    # ### end Alembic commands ###
