"""empty message

Revision ID: 85fbdd72c09b
Revises: 9641fdcfd15e
Create Date: 2020-11-29 16:23:36.745804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fbdd72c09b'
down_revision = '9641fdcfd15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
